### ISSUE TITLE
Windows Build Error

### ISSUE THREAD

**Issue by Peter-J-Jansen** [SDL-Hercules-390/gists#1] opened 2019-11-27 16:13 UTC
I got this build error : 

```
C:\Users\Peter\SDL-extpkgs>xcopy /Y %HOMEPATH%\Downloads\gists\ExtPkgs.cmd*
\Users\Peter\Downloads\gists\ExtPkgs.cmd
\Users\Peter\Downloads\gists\ExtPkgs.cmd.ini
2 File(s) copied

C:\Users\Peter\SDL-extpkgs>ExtPkgs.cmd clone c d s t

cmdline = ExtPkgs.cmd clone c d s t

action         =  CLONE
crypto_repo    = ".\repos\crypto-0"
decnumber_repo = ".\repos\decNumber-0"
softfloat_repo = ".\repos\SoftFloat-0"
telnet_repo    = ".\repos\telnet-0"
install_dir    = "C:\Users\Peter\SDL-extpkgs"
cpu            = "x86"
Cloning into 'crypto-0'...
Cloning into 'decNumber-0'...
Cloning into 'SoftFloat-0'...
Cloning into 'telnet-0'...

All External Packages SUCCESSFULLY cloned!  :))

crypto ...
  64-bit Debug ...
  FAILED!

One or more External Packages has FAILED!  :(

C:\Users\Peter\SDL-extpkgs>
```

The error message being of the good, old "An Error Has Occurred" type, was not so helpful. I tried locating the error, but must admit I was not successful. This has worked in the past for me, but under Windows that must have been one or two years ago. Most recently on macOS (actually10.15.1 Catalina), it worked two days ago. But now, on Windows 10, build 1909, it no longer works.

**Comment by Fish-Git** [comment] 2019-11-27 22:01
Since: a) it works fine for me on Windows 7 x64 with Visual Studio 2008, git 2.20.0 and CMake 3.5.2, and b) it works fine for you on macOS 10.15.1 Catalina, the only logical conclusion I can reach (without examining all of the files in your build directory) is that it has something to do with your Windows 10 installation.

Here's my successful run:

```cmd
C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_GIT\_Fish\extpkgs-VS2008>git --version
git version 2.20.0.windows.1

C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_GIT\_Fish\extpkgs-VS2008>cmake --version
cmake version 3.5.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_GIT\_Fish\extpkgs-VS2008>extpkgs /?

cmdline = extpkgs /?


    NAME

        ExtPkgs.cmd  --  Build and install Hercules External Package(s)

    SYNOPSIS

        ExtPkgs.cmd      { [CLONE | UPDATE]   [C]  [D]  [S]  [T] }

    DESCRIPTION

        ExtPkgs performs a full build and install of each specified
        Hercules External Package.  It is used to automate the
        cloning, updating and/or building and installing of all
        selected External Packages with one simple command (rather
        than having to perform each of the builds individually)
        and ensures that each of them are built the same way.

    ARGUMENTS

        CLONE      Indicates the specified package repositories do
                   not exist yet and need to be git cloned before
                   building.  This option, if specified, must come
                   before the C|D|S|T option(s).

        UPDATE     Indicates the specified package repositories
                   should be git updated before building.  This
                   option, if specified, must come before the
                   C|D|S|T option(s).

        C|D|S|T    Corresponds to which external package(s) you
                   wish to clone, update and/or build and install
                   (crypto, decNumber, SoftFloat and/or telnet,
                   or all four, or any combination thereof)

    EXIT STATUS

        0   Success    All specified external packages successfully
                       cloned, updated and/or built and installed.

        1   Failure    The clone, update, build or install of one
                       or more specified packages has failed.

    NOTES

       The required "ExtPkgs.cmd.ini" control file identifies the
       fixed parameters needed by the script, and is expected to
       exist somewhere in your search PATH.

       The control file must contain statements that identify the
       directory of each external package's repository, as well
       as the common installation directory where each package
       will be installed into.

       The format of the statements is very simple:

            cpu             =  aarch|arm|mips|ppc|sparc|s390x|xscale|x86|unknown
            install_dir     =  <dir>
            crypto_repo     =  <dir>
            decnumber_repo  =  <dir>
            softfloat_repo  =  <dir>
            telnet_repo     =  <dir>

       The specified directory may be either relative or absolute.
       Blank lines and lines beginning with "*", "#" or ";" are
       ignored.

    AUTHOR

        "Fish" (David B. Trout)

    VERSION

        1.4  (November 11, 2019)


C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_GIT\_Fish\extpkgs-VS2008>extpkgs clone c d s t

cmdline = extpkgs clone c d s t

action         =  CLONE
crypto_repo    = ".\repos\crypto-0"
decnumber_repo = ".\repos\decNumber-0"
softfloat_repo = ".\repos\SoftFloat-0"
telnet_repo    = ".\repos\telnet-0"
install_dir    = "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_GIT\_Fish\extpkgs-VS2008"
cpu            = "x86"
Cloning into 'crypto-0'...
Cloning into 'decNumber-0'...
Cloning into 'SoftFloat-0'...
Cloning into 'telnet-0'...

All External Packages SUCCESSFULLY cloned!  :))

crypto ...
  64-bit Debug ...
  SUCCESS!
  64-bit Release ...
  SUCCESS!
  32-bit Debug ...
  SUCCESS!
  32-bit Release ...
  SUCCESS!
decNumber ...
  64-bit Debug ...
  SUCCESS!
  64-bit Release ...
  SUCCESS!
  32-bit Debug ...
  SUCCESS!
  32-bit Release ...
  SUCCESS!
SoftFloat ...
  64-bit Debug ...
  SUCCESS!
  64-bit Release ...
  SUCCESS!
  32-bit Debug ...
  SUCCESS!
  32-bit Release ...
  SUCCESS!
telnet ...
  64-bit Debug ...
  SUCCESS!
  64-bit Release ...
  SUCCESS!
  32-bit Debug ...
  SUCCESS!
  32-bit Release ...
  SUCCESS!

All External Packages SUCCESSFULLY built!  :))

Don't forget to update your 'LIB' and 'INCLUDE' variables to point to
"C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_GIT\_Fish\extpkgs-VS2008\lib" and "C:\Users\Fish\Documents\Visual Stu
dio 2008\Projects\Hercules\_GIT\_Fish\extpkgs-VS2008\include" before building Hercules
or use the '-extpkg "C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_GIT\_Fish\extpkgs-VS2008"' option on your 'makefi
le.bat'
command. (Using the environment variables technique is easier IMO.)

C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_GIT\_Fish\extpkgs-VS2008>vstools detect

C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_GIT\_Fish\extpkgs-VS2008>set vs
vs2005=80
vs2008=90
vs2010=100
vs2012=110
vs2013=120
vs2015=140
vs2017=150
VS90COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\Tools\
vshost=amd64
vsname=vs2008
VSNAMES=vs2017 vs2015 vs2013 vs2012 vs2010 vs2008 vs2005
vsver=90

C:\Users\Fish\Documents\Visual Studio 2008\Projects\Hercules\_GIT\_Fish\extpkgs-VS2008>
```

Since it's failing during the build step, I'm guessing it has something to do with the version of Visual Studio you're using. What version do you have installed? Can you think of anything that might have changed recently on your system? Did you upgrade Visual Studio? Did you upgrade cmake?

I have an _**incredibly old**_ version of Windows 10 installed in a VMware virtual machine that I haven't updated in several _years_ now (I don't even know what version it is!), so it will likely take me a _very long time_ to try this (test this) for myself with the same version of Windows you are using.

The only suggestion I have is to double and triple check everything related, especially the cmake and Visual Studio side of things. In the mean time, if you could post the contents of your ExtPkgs 'build' directory (.zip it and attach it to this github issue) I could take a look at it to see if maybe I can see something.

**Comment by Fish-Git** [comment] 2019-11-27 22:10
p.s. Please .zip your existing 'build' directory (and attach it to this github issue) _**before**_ you try the following:

Try using the command: `extpkgs c d s t` (i.e. _without_ the `CLONE` or `UPDATE` options) to just (re-)build what you've already successfully cloned to see if maybe/hopefully that will work.

Maybe there's a subtle bug somewhere that is causing it to fail when it tries building after cloning, but doesn't occur if you just build without cloning?

That is to say, let's verify the problem is with the _building_ step (since the clone step seems to have been successful), by doing _only_ a build _without_ the clone (since that's already been done).

BUT PLEASE, preserve (save) your existing (failing) 'build' directory _first!_, so I can take a look at it!

Thanks.

**Comment by Peter-J-Jansen** [comment] 2019-11-28 16:41
I agree that it must have something to do with the version of (some of) my building tools!

On another PC (also Windows 10 build 1909) but with just MS VS2019 CE on it, _inclusive of VS2019 git and cmake support stuff_, the ExtPkgs building worked just fine, as the "A Working Windows ExtPkgs.log" in the attached .zip file shows.  The .zip file includes the "SDL-extpkgs-build_failure" directory as requested, perhaps this will be of use if finding the root cause. There is no hurry in this, as I can build already at least on this other PC.

What I have also included in the attached .zip file are some notes of mine on what I had to do to make ExtPkgs work on my Raspberry Pi 4 with its 64 bit ARM processor. Perhaps that support could be added, similar to the newest s390x support, so that my manual stuff would no longer be necessary. (Yes, this should have deserved a separate Issue #; sorry.)

Thanks for the excellent support Fish!

Cheers,

Peter 

* [ExtPkgs Windows Problem.zip](https://github.com/SDL-Hercules-390/gists/files/3902557/ExtPkgs.Windows.Problem.zip)

**Comment by Fish-Git** [comment] 2019-11-28 22:26
The problem (bug) is obvious:

Contents of your failing: `build\crypto\crypto.log`:

&nbsp;
<pre>
    cmdline = "C:\Users\Peter\SDL-extpkgs\repos\crypto-0\build.cmd" --pkgname . --rebuild --cpu x86 --arch 64 --config Debug --install "C:\Users\Peter\SDL-extpkgs"

    Build of 64-bit Debug version of crypto begun on 27-Nov-2019 at 16:48:48.73

    Configuring crypto64.Debug ...

    <i><b>vstools.cmd: ERROR: No supported version of Visual Studio is installed</b></i>

    --------------------------- ENVIRONMENT POOL ---------------------------

    #=C:\Users\Peter\SDL-extpkgs\repos\crypto-0\CMakeLists.txt
    @=c
    action=CLONE
    ALLUSERSPROFILE=C:\ProgramData
    APPDATA=C:\Users\Peter\AppData\Roaming
    arch=64
    blddir=crypto64.Debug

    ... etc ...
</pre>

&nbsp;
It appears the `vstools.cmd` scripts have not been updated to support VS2019 yet. Looking at the existing `vstools.cmd` scripts in each of the crypto, decNumber, SoftFloat and telnet repos, we see on lines 94-102:

```
  set "vs2005=80"
  set "vs2008=90"
  set "vs2010=100"
  set "vs2012=110"
  set "vs2013=120"
  set "vs2015=140"
  set "vs2017=150"

  set "VSNAMES=vs2017 vs2015 vs2013 vs2012 vs2010 vs2008 vs2005"
```

Other lines in the script hint at the same problem: missing VS2019 support. _(Oops!)_

For Hercules, pull request 216 (https://github.com/SDL-Hercules-390/hyperion/pull/216) was made on June 28 of this year that added VS2019 support to Hercules's `vstools.cmd` script (commit https://github.com/SDL-Hercules-390/hyperion/commit/78da7c19570afbda83ec9fc60559e26c2cd9d242) (but it failed to update the script's version string and a few other comments here and there too), but the same change never made it into any of the `vstools.cmd` scripts in any of the External Package repositories! _(Oops!)_

That's my fault. &nbsp; `:(`

I'll fix the version string and other comments in Hercules's vstools script and then copy it over (commit it) to all of the External Package repositories ASAP.

Give me a few minutes...

**Comment by Fish-Git** [comment] 2019-11-29 00:31
DONE!

Please do: `extpkgs UPDATE c d s t` and try again.

Let me know if it works okay or if I screwed something up. Thanks.

p.s. I'll take a look at your Raspberry Pi 4 aarch/aarch64 issue next, but I'm a little confused over the aarch _and_ aarch64 requirement. (Why both? Why not just one or the other? What's the difference? Under what circumstances would you need to specify one or the other?)

**Comment by Peter-J-Jansen** [comment] 2019-11-29 12:41
FIXED!

Everything worked fine this time. 

What I cannot explain is why it _appeared_ to have worked on my other Windows PC, because this one has the same VS2019. This conclusion was merely based on the ExtPkgs "SUUCCESS" messages.  One possible explanation is perhaps that this PC, being a few years older, in the past had older version of MS VS201x installed, even though later on these were un-installed. I looked again at the resulting extpkgs directories, and discovered, as an example, that the build\crypto\crypto.log file contains the error message "The system cannot find the path specified." So perhaps ExtPkgs did not really work on that other PC yesterday.

Anyway, the problem is fixed and can be closed.  Thanks again Fish for this speedy support !

Cheers,

Peter

P.S.: Right now I do not know the answer to your aarch / aarch64 questions.  I remember that initially, I just bluntly tried extpkgs on my RPI4 which failed, I changed to extpkgs.sh.ini file introducing aarch, and then got a linking error message later on during Hercules building which mentioned this aarch64 directory. And the renaming fixed it. But why there is this difference, I don't know. I'll try to find out more.

**Comment by Fish-Git** [comment] 2019-11-29 21:00
> > DONE!
> > 
> > Please do: `extpkgs UPDATE c d s t` and try again.
> > 
> > Let me know if it works okay or if I screwed something up. Thanks.
> 
> FIXED!
> 
> Everything worked fine this time.

Actually, what I _should_ have requested was for you to first _delete_ your existing repos, and then try your original "extpkgs CLONE c d s t"  again (i.e. clone-and-build), since that's what originally failed.

But... I'm satisfied that it should be fixed now.

Closing.

**Closed as completed by Fish-Git** 2019-11-29 21:00 UTC
Labels: bug

**Comment by Fish-Git** [comment] 2019-11-29 21:11
> P.S.: Right now I do not know the answer to your aarch / aarch64 questions. I remember that initially, I just bluntly tried extpkgs on my RPI4 which failed, I changed to extpkgs.sh.ini file introducing aarch, and then got a linking error message later on during Hercules building which mentioned this aarch64 directory. And the renaming fixed it. But why there is this difference, I don't know. I'll try to find out more.

Ah... Yes... Hercules... Of course...

You are correct: it appears Hercules only directly supports `aarch64`, not `aarch`. Why that is, I'm not sure.

Maybe what I need to do is add `aarch` support to Hercules, _and then,_ add `aarch64` support to all of the external packages' `build` scripts too.

(It looks like all of the external package `build` scripts only recognize `aarch`, not `aarch64`, the complete opposite of Hercules, and I think they both need to be kept in sync with each other.)

Let me see if I can devise an easier way to keep the two in sync... (i.e. Hercules's configure.ac and the External Package build scripts)
